index:
    path: /
    controller: App\Controller\IndexController::indexAction

register:
    path: /register
    controller: App\Controller\UserController::registerAction
    methods: ['GET', 'POST']

store_list:
    path: /list/storage
    controller: App\Controller\IndexController::storageListAction

project:
    path: /project/{project}
    controller: App\Controller\ProjectController::getProjectAction
    methods: ['GET']

project_del:
    path: /project/{project}
    controller: App\Controller\ProjectController::deleteProjectAction
    methods: ['DELETE']

project_list:
    path: /projects
    controller: App\Controller\ProjectController::getProjectsAction
    methods: ['GET']

project_create:
    path: /project
    controller: App\Controller\ProjectController::addProjectAction
    methods: ['POST']

project_update:
    path: /project/{project}
    controller: App\Controller\ProjectController::updateProjectAction
    methods: ['PUT']

project_office_list:
    path: /office/projects
    controller: App\Controller\OfficeController::projectListAction
    methods: ['GET']

project_office_create:
    path: /office/project
    controller: App\Controller\OfficeController::projectFormAction
    methods: ['GET', 'POST']

project_office_update:
    path: /office/project/{project}
    controller: App\Controller\OfficeController::projectFormAction
    methods: ['GET', 'POST']

login:
    path: /login
    controller: App\Controller\UserController::loginAction
logout:
    path: /logout
