CREATE DATABASE IF NOT EXISTS tagBeSill CHAR SET utf8 COLLATE utf8_bin;

USE tagBeSill;

CREATE TABLE IF NOT EXISTS Status (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description BLOB NOT NULL
)engine InnoDB;

CREATE TABLE IF NOT EXISTS Project (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title varchar(255) NOT NULL,
	description BLOB NOT NULL,
	image varchar(255) DEFAULT NULL,
	pubDate DATETIME DEFAULT NULL,
	creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	statusId INTEGER UNSIGNED NOT NULL,
	FOREIGN KEY (statusId) REFERENCES Status(id)
) engine InnoDB;

CREATE TABLE IF NOT EXISTS Category(
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description BLOB NOT NULL
)engine InnoDB;

CREATE TABLE IF NOT EXISTS projectCategory(
    projectId INTEGER UNSIGNED,
    categoryId INTEGER UNSIGNED,
    PRIMARY KEY (projectId, categoryId),
    FOREIGN KEY (projectId) REFERENCES Project(id),
    FOREIGN KEY (categoryId) REFERENCES Category(id)
)engine InnoDB;
